services:
  - type: web
    plan: free
    name: Bctchinna
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m Bctchinna 
    repo:  https://github.com/GDNBHARATH448/BCT-userbot
    branch: master
    envVars:
      - key: SUDO_USERS 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: STRING_SESSION1
        sync: false
      - key: MONGO_URL
        sync: false    
    autoDeploy: false
